---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/specializations":
    get:
      summary: Retrives all specializations
      tags:
      - Specializations
      responses:
        '200':
          description: All specializations retrived
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                  required:
                  - id
                  - name
                  - created_at
                  - updated_at
    post:
      summary: Creates a specialization
      tags:
      - Specializations
      parameters:
      - name: name
        in: query
        schema:
          type: string
      responses:
        '200':
          description: specialization created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
                required:
                - id
                - name
                - created_at
                - updated_at
        '422':
          description: invalid request
  "/api/specializations/{id}":
    get:
      summary: Retrives a specialization
      tags:
      - Specializations
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: specialization edited
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
                required:
                - id
                - name
                - created_at
                - updated_at
        '422':
          description: invalid request
    put:
      summary: Edits a specialization
      tags:
      - Specializations
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: name
        in: query
        schema:
          type: string
      responses:
        '200':
          description: specialization edited
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
                required:
                - id
                - name
                - created_at
                - updated_at
        '422':
          description: invalid request
    delete:
      summary: Destroys a specialization
      tags:
      - Specializations
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Specialization has been deleted.
        '422':
          description: invalid request
        '404':
          description: Couldn't find Specialization with 'id'=-
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
